[[annex-a]]
[appendix]
== Abstract Test Suite (Normative)

[[ats_core]]
===  Conformance Class "Core"
[conformance_class]
====
[%metadata]
identifier:: http://www.opengis.net/spec/ogcapi-joins-1/1.0/conf/core
target:: http://www.opengis.net/spec/ogcapi-joins-1/1.0/req/core
classification:: Target Type:Web API
abstract-test:: /conf/core/operations
abstract-test:: /conf/core/http
abstract-test:: /conf/core/root-op
abstract-test:: /conf/core/root-success
abstract-test:: /conf/core/api-definition-op
abstract-test:: /conf/core/api-definition-success
abstract-test:: /conf/core/conformance-op
abstract-test:: /conf/core/conformance-success
====

==== General Tests
===== Operations
include::abstract_tests/core/ATS_operations.adoc[]

===== HTTP
include::abstract_tests/core/ATS_http.adoc[]

==== Landing Page {root}/
include::abstract_tests/core/ATS_root-op.adoc[]

include::abstract_tests/core/ATS_root-success.adoc[]

==== API Definiton path {root}/api (link)
include::abstract_tests/core/ATS_api-definition-op.adoc[]

include::abstract_tests/core/ATS_api-definition-success.adoc[]

==== Conformance {root}/conformance
include::abstract_tests/core/ATS_conformance-op.adoc[]

include::abstract_tests/core/ATS_conformance-success.adoc[]


[[ats_data_joining]]
===  Conformance Class "Data Joining"
[conformance_class]
====
[%metadata]
identifier:: http://www.opengis.net/spec/ogcapi-joins-1/1.0/conf/data-joining
target:: http://www.opengis.net/spec/ogcapi-joins-1/1.0/req/data-joining
classification:: Target Type:Web API
abstract-test:: /conf/data-joining/collections-get-op
abstract-test:: /conf/data-joining/collections-get-success
abstract-test:: /conf/data-joining/collections-get-success-links
abstract-test:: /conf/data-joining/collections-get-success-items
abstract-test:: /conf/data-joining/collections-collectionid-get-op
abstract-test:: /conf/data-joining/collections-collectionid-get-success
abstract-test:: /conf/data-joining/collections-collectionid-get-success-extent
abstract-test:: /conf/data-joining/collections-collectionid-get-success-links
abstract-test:: /conf/data-joining/collections-collectionid-keys-get-op
abstract-test:: /conf/data-joining/collections-collectionid-keys-get-success
abstract-test:: /conf/data-joining/collections-collectionid-keys-get-success-default-key
abstract-test:: /conf/data-joining/collections-collectionid-keys-get-success-links
abstract-test:: /conf/data-joining/collections-collectionid-joins-get-op
abstract-test:: /conf/data-joining/collections-collectionid-joins-get-success
abstract-test:: /conf/data-joining/collections-collectionid-joins-get-success-limit
abstract-test:: /conf/data-joining/collections-collectionid-joins-get-success-limit-unsupported
abstract-test:: /conf/data-joining/collections-collectionid-joins-get-success-datetime
abstract-test:: /conf/data-joining/collections-collectionid-joins-get-success-paged-response
abstract-test:: /conf/data-joining/collections-collectionid-joins-get-success-numberMatched
abstract-test:: /conf/data-joining/collections-collectionid-joins-get-success-numberReturned
abstract-test:: /conf/data-joining/collections-collectionid-joins-get-success-items
abstract-test:: /conf/data-joining/collections-collectionid-joins-get-success-links
abstract-test:: /conf/data-joining/collections-collectionid-joins-get-success-items-links
abstract-test:: /conf/data-joining/collections-collectionid-joins-get-success-timeStamp
abstract-test:: /conf/data-joining/collections-collectionid-joins-post-op
abstract-test:: /conf/data-joining/collections-collectionid-joins-post-success
abstract-test:: /conf/data-joining/collections-collectionid-joins-joinid-get-op
abstract-test:: /conf/data-joining/collections-collectionid-joins-joinid-get-success
abstract-test:: /conf/data-joining/collections-collectionid-joins-joinid-get-success-links
====

==== Collections {root}/collections
include::abstract_tests/data-joining/ATS_collections-get-op.adoc[]

include::abstract_tests/data-joining/ATS_collections-get-success.adoc[]

include::abstract_tests/data-joining/ATS_collections-get-success-links.adoc[]

include::abstract_tests/data-joining/ATS_collections-get-success-items.adoc[]

==== Collection {root}/collections/{collectionId}
include::abstract_tests/data-joining/ATS_collections-collectionid-get-op.adoc[]

include::abstract_tests/data-joining/ATS_collections-collectionid-get-success.adoc[]

include::abstract_tests/data-joining/ATS_collections-collectionid-get-success-extent.adoc[]

include::abstract_tests/data-joining/ATS_collections-collectionid-get-success-links.adoc[]

==== Collection Key Fields {root}/collections/{collectionId}/keys
include::abstract_tests/data-joining/ATS_collections-collectionid-keys-get-op.adoc[]

include::abstract_tests/data-joining/ATS_collections-collectionid-keys-get-success.adoc[]

include::abstract_tests/data-joining/ATS_collections-collectionid-keys-get-success-default-key.adoc[]

include::abstract_tests/data-joining/ATS_collections-collectionid-keys-get-success-links.adoc[]


==== Joins Sources {root}/collections/{collectionId}/joins
include::abstract_tests/data-joining/ATS_collections-collectionid-joins-get-op.adoc[]

include::abstract_tests/data-joining/ATS_collections-collectionid-joins-get-success.adoc[]

include::abstract_tests/data-joining/ATS_collections-collectionid-joins-get-success-limit.adoc[]

include::abstract_tests/data-joining/ATS_collections-collectionid-joins-get-success-limit-unsupported.adoc[]

include::abstract_tests/data-joining/ATS_collections-collectionid-joins-get-success-datetime.adoc[]

include::abstract_tests/data-joining/ATS_collections-collectionid-joins-get-success-paged-response.adoc[]

include::abstract_tests/data-joining/ATS_collections-collectionid-joins-get-success-numberMatched.adoc[]

include::abstract_tests/data-joining/ATS_collections-collectionid-joins-get-success-numberReturned.adoc[]

include::abstract_tests/data-joining/ATS_collections-collectionid-joins-get-success-items.adoc[]

include::abstract_tests/data-joining/ATS_collections-collectionid-joins-get-success-links.adoc[]

include::abstract_tests/data-joining/ATS_collections-collectionid-joins-get-success-items-links.adoc[]

include::abstract_tests/data-joining/ATS_collections-collectionid-joins-get-success-timeStamp.adoc[]

==== Join Source Creation {root}/collections/{collectionId}/joins
include::abstract_tests/data-joining/ATS_collections-collectionid-joins-post-op.adoc[]

include::abstract_tests/data-joining/ATS_collections-collectionid-joins-post-success.adoc[]

==== Join Source {root}/collections/{collectionId}/joins/{joinId}
include::abstract_tests/data-joining/ATS_collections-collectionid-joins-joinid-get-op.adoc[]

include::abstract_tests/data-joining/ATS_collections-collectionid-joins-joinid-get-success.adoc[]

include::abstract_tests/data-joining/ATS_collections-collectionid-joins-joinid-get-success-links.adoc[]

[[ats_join_source_delete]]
===  Conformance Class "Join Source Delete"
[conformance_class]
====
[%metadata]
identifier:: http://www.opengis.net/spec/ogcapi-joins-1/1.0/conf/join-source-delete
target:: http://www.opengis.net/spec/ogcapi-joins-1/1.0/req/join-source-delete
classification:: Target Type:Web API
abstract-test:: /conf/join-source-delete/collections-collectionid-joins-joinid-delete-op
abstract-test:: /conf/join-source-delete/collections-collectionid-joins-joinid-delete-success
====

==== Join Source Delete {root}/collections/{collectionId}/joins/{joinId}
include::abstract_tests/join-source-delete/ATS_collections-collectionid-joins-joinid-delete-op.adoc[]

include::abstract_tests/join-source-delete/ATS_collections-collectionid-joins-joinid-delete-success.adoc[]

[[ats_file_joining]]
===  Conformance Class "File Joining"
[conformance_class]
====
[%metadata]
identifier:: http://www.opengis.net/spec/ogcapi-joins-1/1.0/conf/file-joining
target:: http://www.opengis.net/spec/ogcapi-joins-1/1.0/req/file-joining
classification:: Target Type:Web API
abstract-test:: /conf/file-joining/filejoin-post-op
abstract-test:: /conf/file-joining/filejoin-post-success
abstract-test:: /conf/file-joining/filejoin-post-success-attribute-data-file-csv-multiple-keys
abstract-test:: /conf/file-joining/filejoin-post-success-attribute-data-file-csv-attribute-names
====

include::abstract_tests/file-joining/ATS_filejoin-post-op.adoc[]

include::abstract_tests/file-joining/ATS_filejoin-post-success.adoc[]

include::abstract_tests/file-joining/ATS_filejoin-post-success-attribute-data-file-csv-multiple-keys.adoc[]

include::abstract_tests/file-joining/ATS_filejoin-post-success-attribute-data-file-csv-attribute-names.adoc[]


[[ats_input_file_upload]]
===  Conformance Class "Input File Upload"
[conformance_class]
====
[%metadata]
identifier:: http://www.opengis.net/spec/ogcapi-joins-1/1.0/conf/input-file-upload
target:: http://www.opengis.net/spec/ogcapi-joins-1/1.0/req/input-file-upload
classification:: Target Type:Web API
abstract-test:: /conf/input-file-upload/right-dataset-file-join-source-creation
abstract-test:: /conf/input-file-upload/right-dataset-file-file-joining
abstract-test:: /conf/input-file-upload/left-dataset-file-file-joining
====

include::abstract_tests/input-file-upload/ATS_right-dataset-file-join-source-creation.adoc[]

include::abstract_tests/input-file-upload/ATS_right-dataset-file-file-joining.adoc[]

include::abstract_tests/input-file-upload/ATS_left-dataset-file-file-joining.adoc[]


[[ats_input_http_ref]]
===  Conformance Class "File Referencing with URL"
[conformance_class]
====
[%metadata]
identifier:: http://www.opengis.net/spec/ogcapi-joins-1/1.0/conf/input-http-ref
target:: http://www.opengis.net/spec/ogcapi-joins-1/1.0/req/input-http-ref
classification:: Target Type:Web API
abstract-test:: /conf/input-http-ref/right-dataset-url-join-source-creation
abstract-test:: /conf/input-http-ref/right-dataset-url-file-joining
abstract-test:: /conf/input-http-ref/left-dataset-url-file-joining
====

include::abstract_tests/input-http-ref/ATS_right-dataset-url-join-source-creation.adoc[]

include::abstract_tests/input-http-ref/ATS_right-dataset-url-file-joining.adoc[]

include::abstract_tests/input-http-ref/ATS_left-dataset-url-file-joining.adoc[]


[[ats_input_csv]]
===  Conformance Class "CSV File Input"
[conformance_class]
====
[%metadata]
identifier:: http://www.opengis.net/spec/ogcapi-joins-1/1.0/conf/input-csv
target:: http://www.opengis.net/spec/ogcapi-joins-1/1.0/req/input-csv
classification:: Target Type:Web API
abstract-test:: /conf/input-csv/right-dataset-format-join-source-creation
abstract-test:: /conf/input-csv/right-dataset-format-file-joining
====

include::abstract_tests/input-csv/ATS_right-dataset-format-join-source-creation.adoc[]
include::abstract_tests/input-csv/ATS_right-dataset-format-file-joining.adoc[]



[[ats_input_geojson]]
===  Conformance Class "GeoJSON File Input"
[conformance_class]
====
[%metadata]
identifier:: http://www.opengis.net/spec/ogcapi-joins-1/1.0/conf/input-geojson
target:: http://www.opengis.net/spec/ogcapi-joins-1/1.0/req/input-geojson
classification:: Target Type:Web API
abstract-test:: /conf/input-geojson/left-dataset-format-file-joining
====

include::abstract_tests/input-geojson/ATS_left-dataset-format-file-joining.adoc[]


[[ats_html]]
===  Conformance Class "HTML"
[conformance_class]
====
[%metadata]
identifier:: http://www.opengis.net/spec/ogcapi-joins-1/1.0/conf/html
target:: http://www.opengis.net/spec/ogcapi-joins-1/1.0/req/html
classification:: Target Type:Web API
abstract-test:: /conf/html/definition
abstract-test:: /conf/html/content
====

==== HTML Definition
include::abstract_tests/html/ATS_html-definition.adoc[]

==== HTML Content
include::abstract_tests/html/ATS_html-content.adoc[]



[[ats_json]]
===  Conformance Class "JSON"
[conformance_class]
====
[%metadata]
identifier:: http://www.opengis.net/spec/ogcapi-joins-1/1.0/conf/json    
target:: http://www.opengis.net/spec/ogcapi-joins-1/1.0/req/json
classification:: Target Type:Web API
abstract-test:: /conf/json/json-definition
abstract-test:: /conf/json/json-content
====

==== JSON Definition
include::abstract_tests/json/ATS_json-definition.adoc[]

==== JSON Content
include::abstract_tests/json/ATS_json-content.adoc[]


[[ats_geojson]]
===  Conformance Class "GeoJSON"
[conformance_class]
====
[%metadata]
identifier:: http://www.opengis.net/spec/ogcapi-joins-1/1.0/conf/geojson    
target:: http://www.opengis.net/spec/ogcapi-joins-1/1.0/req/geojson
classification:: Target Type:Web API
abstract-test:: /conf/geojson/geojson-file-joining
====

==== File Joining
include::abstract_tests/geojson/ATS_geojson-file-joining.adoc[]
